#!/bin/sh

wmname LG3D

source ~/.config/bspwm/colors.bash
~/.screenlayout/two.sh

killall nitrogen

nitrogen --restore

# MONITOR
bspc monitor HDMI-A-0 -n Monitor0 -d I II III
bspc monitor eDP -n Monitor1 -d IV V VI
bspc monitor HDMI-A-0 -s eDP

# COLORES Y VENTANAS
bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config focused_border_color "$black6"
bspc config normal_border_color "$black1"
bspc config active_border_color "$black1"
bspc config presel_feedback_color "$black1"

#bspc rule -a blueberry desktop='^3' state=floating manage=off
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bash .config/polybar/launch.sh
# COMPOSITOR
picom --config ~/.config/picom/picom.conf
# SXHKD
pgrep -x sxhkd > /dev/null || sxhkd &


